# Site information
title: DEVELOPER IN THE SHELL
author: Tomohiro TAIRA

# Jekyll settings
permalink: /posts/:title
exclude:
  - _scss
  - _coffee
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - robots.txt
include: ['.well-known']

# Plugins
#   Adding Jekyll plugins to a GitHub Pages site - User Documentation
#   https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-github-metadata

# Jekyll Feed plugin configuration
# https://github.com/jekyll/jekyll-feed
feed:
  path: atom.xml
